syntax = "proto3";

package lemline.internal.v1;

import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";
import "internal/common.proto";

option java_multiple_files = true;
option java_package = "com.lemline.messages.internal.v1";

message NodeStateProto {
    oneof state {
        RootStateProto root_state = 1;
        DoStateProto do_state = 2;
        ForStateProto for_state = 3;
        ForeachStateProto foreach_state = 4;
        TaskStateProto task_state = 5;
        CallFunctionStateProto call_function_state = 6;
        TryStateProto try_state = 7;
    }
}

message RootStateProto {
    google.protobuf.Timestamp started_at = 1;
    string workflow_id = 2;
    google.protobuf.Value workflow_input_json = 3;
    google.protobuf.Struct context_json = 4;
    bool has_waiting_parent = 5;
}

message DoStateProto {
    google.protobuf.Timestamp started_at = 1;
    int32 index = 2;
}

message ForStateProto {
    google.protobuf.Timestamp started_at = 1;
    google.protobuf.ListValue collection_json = 2;
    int32 index = 3;
    string for_each = 4;
    string for_at = 5;
}

message ForeachStateProto {
    google.protobuf.Timestamp started_at = 1;
    google.protobuf.Value item_json = 2;
    int32 index = 3;
    string item_var = 4;
    string index_var = 5;
}

message TaskStateProto {
    google.protobuf.Timestamp started_at = 1;
}

message CallFunctionStateProto {
    google.protobuf.Timestamp started_at = 1;
    bool entered = 2;
}

message TryStateProto {
    google.protobuf.Timestamp started_at = 1;
    google.protobuf.Value transformed_input_json = 2;
    int32 attempt_index = 3;
    bool running_catch = 4;
    InternalErrorProto last_error = 5;
    string error_as = 6;
    bool has_started = 7;
}
