// SPDX-License-Identifier: BUSL-1.1
package com.lemline.runner.models

import com.lemline.common.values.IDV7
import kotlin.time.ExperimentalTime
import kotlin.time.Instant
import kotlinx.serialization.ExperimentalSerializationApi

/**
 * Model representing an accumulated CloudEvent for a listener.
 *
 * Implements [WithId] to enable [WithIdRepository] operations.
 *
 * Used for strategies that require multiple events:
 * - **ALL**: One event per filter, completion when all filters matched
 * - **ANY with until**: Accumulate events until condition is met
 *
 * For simple strategies (ONE, ANY without until), the event is stored
 * directly in the [ListenerModel.event] column.
 *
 * ## Idempotency
 *
 * The primary key [id] is derived deterministically:
 * - **ALL**: `listenerId.derive("-filter-$filterIndex")`
 * - **ANY+until**: `listenerId.derive("-event-${cloudEvent.id}")`
 *
 * This ensures duplicate inserts fail on PK conflict, making the operation idempotent.
 *
 * ## Filter Index
 *
 * - **ALL strategy**: Explicit value (0, 1, 2...) matching the filter that was satisfied
 * - **ANY+until**: Auto-generated by database (used only for ordering)
 *
 * The UNIQUE(listener_id, filter_index) constraint ensures one event per filter for ALL strategy.
 *
 * @see ListenerModel for the parent listener
 */
@ExperimentalSerializationApi
@ExperimentalTime
data class ListenerEventModel(
    /** Unique identifier - derived for idempotency */
    override val id: IDV7,

    /** Reference to the parent listener */
    val listenerId: IDV7,

    /**
     * Filter index.
     * - For ALL: explicit filter index (0, 1, 2...)
     * - For ANY+until: null (let DB auto-generate)
     */
    val filterIndex: Int?,

    /** CloudEvent data as JSON string */
    val event: String,

    /** Creation timestamp */
    val createdAt: Instant? = null
) : WithId
