services:
  pulsar:
    image: apachepulsar/pulsar:latest
    command: >
      bin/pulsar standalone
    ports:
      - "6650:6650"  # Pulsar broker port
      - "8080:8080"  # Pulsar admin port
    volumes:
      - pulsar-data:/pulsar/data
    environment:
      PULSAR_MEM: "-Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pulsar-data:
  db-data:
