syntax = "proto3";

package lemline.internal.v1;

import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";
import "internal/common.proto";
import "internal/state/node_stack.proto";
import "internal/workflow/configs.proto";

option java_multiple_files = true;
option java_package = "com.lemline.messages.internal.v1";

message WorkflowEventProto {
    oneof event {
        WorkflowCompletedProto workflow_completed = 1;
        WorkflowFailedProto workflow_failed = 2;
        ForkBranchCompletedProto fork_branch_completed = 3;
        ForkBranchFailedProto fork_branch_failed = 4;
        ForEachCompletedProto for_each_completed = 5;
        TaskScheduledProto task_scheduled = 6;
        WaitStartedProto wait_started = 7;
        TaskRetryScheduledProto task_retry_scheduled = 8;
        RunWorkflowStartedProto run_workflow_started = 9;
        ForkStartedProto fork_started = 10;
        ListenStartedProto listen_started = 11;
        EmitStartedProto emit_started = 12;
        CallHttpStartedProto call_http_started = 13;
        RunScriptStartedProto run_script_started = 14;
        RunShellStartedProto run_shell_started = 15;
    }
}

message WorkflowCompletedProto {
    NodeStackProto node_stack = 1;
    google.protobuf.Value output_json = 2;
    google.protobuf.Timestamp completed_at = 3;
}

message WorkflowFailedProto {
    NodeStackProto node_stack = 1;
    google.protobuf.Value input_json = 2;
    google.protobuf.Value output_json = 3;
    FlowDirectiveProto flow_directive = 4;
    InternalErrorProto error = 5;
    google.protobuf.Timestamp failed_at = 6;
}

message ForkBranchCompletedProto {
    NodeStackProto node_stack = 1;
    string branch_position = 2;
    google.protobuf.Value branch_output_json = 3;
    google.protobuf.Timestamp completed_at = 4;
}

message ForkBranchFailedProto {
    NodeStackProto node_stack = 1;
    string branch_position = 2;
    InternalErrorProto error = 3;
    google.protobuf.Timestamp failed_at = 4;
}

message ForEachCompletedProto {
    NodeStackProto node_stack = 1;
    google.protobuf.Value output_json = 2;
}

message TaskScheduledProto {
    NodeStackProto node_stack = 1;
    string node_position = 2;
    google.protobuf.Value input_json = 3;
    FlowDirectiveProto flow_directive = 4;
}

message WaitStartedProto {
    NodeStackProto node_stack = 1;
    google.protobuf.Value output_json = 2;
    WaitConfigProto config = 3;
}

message TaskRetryScheduledProto {
    NodeStackProto node_stack = 1;
    string node_position = 2;
    google.protobuf.Value input_json = 3;
    FlowDirectiveProto flow_directive = 4;
    google.protobuf.Timestamp retry_at = 5;
}

message RunWorkflowStartedProto {
    NodeStackProto node_stack = 1;
    google.protobuf.Value input_json = 2;
    RunWorkflowConfigProto config = 3;
}

message ForkStartedProto {
    NodeStackProto node_stack = 1;
    google.protobuf.Value input_json = 2;
}

message ListenStartedProto {
    NodeStackProto node_stack = 1;
    google.protobuf.Value output_json = 2;
    ListenConfigProto config = 3;
}

message EmitStartedProto {
    NodeStackProto node_stack = 1;
    google.protobuf.Value input_json = 2;
    EmitConfigProto config = 3;
}

message CallHttpStartedProto {
    NodeStackProto node_stack = 1;
    google.protobuf.Value input_json = 2;
    CallHttpConfigProto config = 3;
}

message RunScriptStartedProto {
    NodeStackProto node_stack = 1;
    google.protobuf.Value input_json = 2;
    RunScriptConfigProto config = 3;
}

message RunShellStartedProto {
    NodeStackProto node_stack = 1;
    google.protobuf.Value input_json = 2;
    RunShellConfigProto config = 3;
}
