package com.lemline.swruntime.sw.errors

import com.fasterxml.jackson.annotation.*

/**
 * Represents an error that occurs during the execution of a workflow.
 *
 * @param errorType Error's type
 * @param status The status code generated by the origin for this occurrence of the error.
 * @param instance A JSON Pointer used to reference the component the error originates from.
 * @param title A short, human-readable summary of the error or a runtime expression
 * @param details A human-readable explanation specific to this occurrence of the error or a runtime expression
 *
 * cf. https://github.com/serverlessworkflow/specification/blob/main/dsl-reference.md#error
 */
@JsonPropertyOrder("type", "status", "instance", "title", "detail")
data class WorkflowError(
    @JsonIgnore
    val errorType: WorkflowErrorType,
    val status: Int = errorType.defaultStatus,
    val instance: String? = null,
    val title: String? = null,
    val details: String? = null,
) {
    val type = "$URI_BASE/${errorType.type}"

    @JsonCreator  // Use this constructor for deserialization
    constructor(
        @JsonProperty("type") type: String,
        @JsonProperty("status") status: Int? = null,
        @JsonProperty("instance") instance: String? = null,
        @JsonProperty("title") title: String? = null,
        @JsonProperty("detail") detail: String? = null
    ) : this(
        errorType = WorkflowErrorType.entries.first { "$URI_BASE/${it.type}" == type },
        status = status ?: WorkflowErrorType.entries.first { "$URI_BASE/${it.type}" == type }.defaultStatus,
        instance = instance,
        title = title,
        details = detail
    )

    companion object {
        private const val URI_BASE = "https://serverlessworkflow.io/spec/1.0.0/errors"
    }
}

enum class WorkflowErrorType(val type: String, val defaultStatus: Int) {
    // Validation errors
    VALIDATION("validation", 400),

    // Authentication errors 
    AUTHENTICATION("authentication", 401),

    // Authorization errors 
    AUTHORIZATION("authorization", 403),

    // Resource not found errors 
    NOT_FOUND("not-found", 404),

    // Timeout errors   
    TIMEOUT("timeout", 408),

    // Communication errors 
    COMMUNICATION("communication", 500),

    // Expression evaluation errors 
    EXPRESSION("expression", 400),

    // Internal errors 
    INTERNAL("internal", 500);

    @JsonValue
    fun toJson(): String = type
}