// SPDX-License-Identifier: BUSL-1.1
package com.lemline.core.errors

import com.lemline.core.nodes.NodePosition
import kotlinx.serialization.Serializable

/**
 * Represents an error that occurs during the execution of a workflow.
 *
 * @param type Error's type
 * @param status The status code generated by the origin for this occurrence of the error.
 * @param instance A JSON Pointer used to reference the component the error originates from.
 * @param title A short, human-readable summary of the error or a runtime expression
 * @param details A human-readable explanation specific to this occurrence of the error or a runtime expression
 *
 * cf. https://github.com/serverlessworkflow/specification/blob/main/dsl-reference.md#error
 */
@Serializable
data class WorkflowError(
    val type: String,
    val status: Int,
    val instance: String,
    val title: String? = null,
    val details: String? = null,
) {
    // Use this constructor for internal use
    constructor(
        errorType: WorkflowErrorType,
        status: Int = errorType.defaultStatus,
        position: NodePosition,
        title: String? = null,
        details: String? = null,
    ) : this(
        type = "$URI_BASE/${errorType.type}",
        status = status,
        instance = position.jsonPointer.toString(),
        title = title,
        details = details,
    )

    companion object {
        private const val URI_BASE = "https://serverlessworkflow.io/spec/1.0.0/errors"
    }
}
