// SPDX-License-Identifier: BUSL-1.1
package com.lemline.core.errors

import com.lemline.common.json.LemlineJson
import com.lemline.common.values.NodePosition
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


sealed class WorkflowException : RuntimeException()

/**
 * Internal Exception thrown during the execution of a workflow.
 *
 * This exception is used to propagate errors that occur during workflow execution.
 * In the new execution model, it's caught by CompleteOrchestrator which finds
 * the appropriate TryTask handler.
 *
 * @property error The workflow error associated with this exception.
 */
data class InternalException(
    val error: Error
) : WorkflowException() {

    /**
     * Represents an error that occurs during the execution of a workflow.
     *
     * @param type Error's type
     * @param status The status code generated by the origin for this occurrence of the error.
     * @param position A JSON Pointer used to reference the component the error originates from.
     * @param title A short, human-readable summary of the error or a runtime expression
     * @param details A human-readable explanation specific to this occurrence of the error or a runtime expression
     *
     * cf. https://github.com/serverlessworkflow/specification/blob/main/dsl-reference.md#error
     */
    @Serializable
    data class Error(
        val type: String,
        val status: Int,
        @SerialName("instance")
        val position: String,
        val title: String? = null,
        val details: String? = null,
    ) {
        // Use this constructor for internal use
        constructor(
            errorType: WorkflowErrorType,
            status: Int = errorType.defaultStatus,
            position: NodePosition,
            title: String? = null,
            details: String? = null,
        ) : this(
            type = "$URI_BASE/${errorType.type}",
            status = status,
            position = position.toString(),
            title = title,
            details = details,
        )

        fun toJsonPrettyString(): String = LemlineJson.encodeToPrettyString(this)

        companion object Companion {
            private const val URI_BASE = "https://serverlessworkflow.io/spec/1.0.0/errors"

            fun from(e: Exception, position: NodePosition) = when (e) {
                is InternalException -> e.error
                else -> Error(
                    errorType = WorkflowErrorType.RUNTIME,
                    position = position,
                    title = e.message,
                    details = e.stackTraceToString(),
                )
            }
        }
    }
}
