// SPDX-License-Identifier: BUSL-1.1
package com.lemline.core.errors

import com.lemline.common.json.LemlineJson
import com.lemline.common.values.WorkflowName
import com.lemline.common.values.WorkflowNamespace
import com.lemline.common.values.WorkflowVersion
import com.lemline.core.nodes.NodePosition
import com.lemline.core.states.ForkState
import com.lemline.core.states.RunState
import com.lemline.core.states.WaitState
import kotlin.time.ExperimentalTime
import kotlin.time.Instant
import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

sealed class WorkflowException : RuntimeException()

/**
 * Internal Exception thrown during the execution of a workflow.
 *
 * This exception is used to propagate errors that occur during workflow execution.
 * In the new execution model, it's caught by CompleteOrchestrator which finds
 * the appropriate TryTask handler.
 *
 * @property error The workflow error associated with this exception.
 */
data class InternalException(
    val error: Error
) : WorkflowException() {

    /**
     * Represents an error that occurs during the execution of a workflow.
     *
     * @param type Error's type
     * @param status The status code generated by the origin for this occurrence of the error.
     * @param instance A JSON Pointer used to reference the component the error originates from.
     * @param title A short, human-readable summary of the error or a runtime expression
     * @param details A human-readable explanation specific to this occurrence of the error or a runtime expression
     *
     * cf. https://github.com/serverlessworkflow/specification/blob/main/dsl-reference.md#error
     */
    @Serializable
    data class Error(
        val type: String,
        val status: Int,
        val instance: String,
        val title: String? = null,
        val details: String? = null,
    ) {
        // Use this constructor for internal use
        constructor(
            errorType: WorkflowErrorType,
            status: Int = errorType.defaultStatus,
            position: NodePosition,
            title: String? = null,
            details: String? = null,
        ) : this(
            type = "$URI_BASE/${errorType.type}",
            status = status,
            instance = position.positionPointer.toString(),
            title = title,
            details = details,
        )

        fun toJsonPrettyString(): String = LemlineJson.encodeToPrettyString(this)

        companion object Companion {
            private const val URI_BASE = "https://serverlessworkflow.io/spec/1.0.0/errors"

            fun fromUnexpectedException(e: Exception, position: NodePosition) = Error(
                errorType = WorkflowErrorType.RUNTIME,
                position = position,
                title = e.message,
                details = e.stackTraceToString(),
            )
        }
    }
}

/**
 * Exception indicating that a child workflow should be started.
 *
 * This exception serves as a marker to indicate the initiation of a child workflow
 * during a larger workflow process. It carries configuration details associated
 * with the child workflow, encapsulated within the [Config] instance.
 */
data class RunWorkflowException(
    val state: RunState,
    val transformedInput: JsonElement,
    val config: Config
) : WorkflowException() {

    /**
     * Configuration details required to initiate a child workflow.
     *
     * This data class encapsulates the metadata and input parameters needed to
     * start a child workflow instance within a larger workflow process.
     *
     * @property namespace The namespace of the child workflow, used to scope workflows within an environment.
     * @property name The name of the child workflow to be executed.
     * @property version The version of the child workflow.
     * @property input The input provided to the child workflow.
     * @property sync Indicates whether the parent workflow should wait for the child workflow to complete.
     */
    @Serializable
    data class Config(
        val namespace: WorkflowNamespace,
        val name: WorkflowName,
        val version: WorkflowVersion,
        val input: JsonElement,
        val sync: Boolean
    )
}


/**
 * Exception indicating that a wait has been requested during a workflow's execution.
 *
 * This exception is thrown to signal that a delay or pause, defined by a [Config],
 * has been incorporated into the workflow's control flow. It can be used to coordinate
 * asynchronous operations or introduce timed pauses in workflow processing.
 *
 * @property config The configuration specifying the details of the wait, including the delay duration.
 */
@ExperimentalTime
data class WaitException(
    val state: WaitState,
    val transformedInput: JsonElement,
    val config: Config
) : WorkflowException() {

    /**
     * Configuration for specifying the wait duration in a workflow task.
     *
     * This configuration is used to indicate a target timestamp until which
     * a delay or pause is requested during a workflow's execution. It is typically
     * used in conjunction with orchestrators to manage timed pauses or schedule
     * task execution at a specific time.
     *
     * @property waitUntil The timestamp indicating when the wait should end.
     */
    @Serializable
    data class Config(
        @Contextual val waitUntil: Instant
    )
}

/**
 * Exception indicating that fork branches should be executed.
 *
 * This exception is thrown when a fork task needs to execute its branches.
 * The orchestrator catches this and either:
 * - ExecutionMode.Complete: Executes branches in parallel using coroutines
 * - ExecutionMode.Async: Returns WorkflowState.RunningFork for runner to schedule
 *
 * All fork configuration (compete mode, branches) is derived from the Node<ForkTask>
 * that threw this exception. Only the transformedInput needs to be carried.
 *
 * Similar to WaitWorkflowException pattern.
 */
@ExperimentalTime
data class ForkException(
    val state: ForkState,
    val transformedInput: JsonElement
) : WorkflowException()
