// SPDX-License-Identifier: BUSL-1.1
package com.lemline.core.states

import com.lemline.common.values.WorkflowId
import com.lemline.core.errors.InternalException
import com.lemline.core.errors.RunWorkflowException
import com.lemline.core.json.LemlineJson
import com.lemline.core.nodes.NodePosition
import com.lemline.core.workflows.FlowDirective
import kotlin.time.Clock
import kotlin.time.ExperimentalTime
import kotlin.time.Instant
import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * Result types returned by WorkflowOrchestrator when it detects a stopping point
 * during workflow execution.
 *
 * The WorkflowOrchestrator executes workflows step-by-step and pauses at specific
 * boundaries (activities, delays, sub-workflows) to allow the runner to persist
 * state and resume execution in different workers.
 */
@Serializable
sealed class WorkflowState {
    abstract val taskStates: TaskStates
    abstract val nodePosition: NodePosition

    open fun toJsonString(): String = LemlineJson.encodeToString(this)

    companion object {
        fun fromJsonString(jsonString: String): WorkflowState = LemlineJson.decodeFromString(jsonString)
    }

    val workflowId: WorkflowId get() = (taskStates[NodePosition.root] as RootState).workflowId

    val hasWaitingParent: Boolean get() = (taskStates[NodePosition.root] as RootState).hasWaitingParent
}

@Serializable
sealed class WorkflowCommand : WorkflowState() {

    override fun toJsonString(): String = LemlineJson.encodeToString(this)

    companion object {
        fun fromJsonString(jsonString: String): WorkflowCommand = LemlineJson.decodeFromString(jsonString)
    }

//    /**
//     * Represents the initial command to start the execution of a workflow.
//     *
//     * This class is part of the workflow orchestration and defines the starting point for
//     * the execution of a workflow. It includes the input required for the workflow,
//     * the unique identifier for the workflow, and a flag indicating whether the workflow
//     * has a parent workflow.
//     *
//     * @property workflowInput The input parameters for the workflow execution.
//     * @property workflowId The unique identifier of the workflow.
//     * @property hasWaitingParent Indicates if the workflow is initiated by a parent workflow.
//     */
//    @Serializable
//    @ExperimentalTime
//    data class Start(
//        val workflowId: WorkflowId,
//        val workflowInput: JsonElement,
//        val hasWaitingParent: Boolean,
//        val startedAt: Instant
//    ) : WorkflowCommand() {
//
//        override val taskStates: TaskStates = mapOf()
//        override val nodePosition = NodePosition.root
//
//        override fun toString() = "${this::class.simpleName}(" +
//            "workflowId=$workflowId" +
//            ", workflowInput=$workflowInput" +
//            ", hasWaitingParent=$hasWaitingParent" +
//            ", startedAt=$startedAt" +
//            ")"
//    }

    /**
     * Represents a command to resume workflow execution from a specific task.
     *
     * @property taskStates The current states of tasks in the workflow.
     * @property nodePosition The position of the task within the workflow node structure.
     * @property rawInput The raw input data provided for resuming the workflow task.
     * @property flowDirective Optional directive specifying the transition behavior for the workflow.
     */
    @Serializable
    data class ResumeFromTask(
        override val taskStates: TaskStates,
        override val nodePosition: NodePosition,
        val rawInput: JsonElement,
        val flowDirective: FlowDirective?
    ) : WorkflowCommand() {
        override fun toString() = "${this::class.simpleName}(" +
            "nodePosition=$nodePosition" +
            ", rawInput=$rawInput" +
            ", flowDirective=$flowDirective" +
            ", states=${taskStates.map { it.key.toString() + "=" + it.value }}" +
            ")"

        @ExperimentalTime
        fun duplicate(workflowId: WorkflowId): ResumeFromTask {
            val rootState = taskStates[NodePosition.root] as RootState
            return copy(
                taskStates = taskStates + mapOf(NodePosition.root to rootState.copy(workflowId = workflowId))
            )
        }
    }

    /**
     * Represents a workflow command to resume execution from a previously started task.
     *
     * @property taskStates Represents a map containing the states of tasks in the workflow.
     * Each task state signifies the current progress or completion of a task.
     * @property nodePosition Represents the position of the current node in the workflow.
     * The node position is used to identify and continue from the last execution point.
     * @property rawOutput Contains the raw output generated by the started task. This
     * value might act as input to the subsequent nodes in the workflow graph.
     */
    @Serializable
    data class ResumeFromStartedTask(
        override val taskStates: TaskStates,
        override val nodePosition: NodePosition,
        val rawOutput: JsonElement,
    ) : WorkflowCommand() {
        override fun toString() = "${this::class.simpleName}(" +
            "nodePosition=$nodePosition" +
            ", rawOutput=$rawOutput" +
            ", states=${taskStates.map { it.key.toString() + "=" + it.value }}" +
            ")"
    }
}

@Serializable
sealed class WorkflowEvent : WorkflowState() {

    override fun toJsonString(): String = LemlineJson.encodeToString(this)

    companion object {
        fun fromJsonString(jsonString: String): WorkflowEvent = LemlineJson.decodeFromString(jsonString)
    }

    /**
     * Workflow execution completed successfully.
     *
     * This indicates that the entire workflow has finished executing and
     * there are no more steps to process. The runner should mark the workflow
     * instance as complete and emit the final output.
     *
     * @property output The final output dataset from the workflow
     */
    @ExperimentalTime
    @Serializable
    data class WorkflowCompleted(
        val output: JsonElement,
        val completedAt: Instant,
        override val taskStates: TaskStates,
    ) : WorkflowEvent() {
        override val nodePosition: NodePosition = NodePosition.root

        override fun toString() = "${this::class.simpleName}(" +
            "output=$output" +
            ")"
    }

    /**
     * Represents a failure in a workflow process, encapsulating details about the states and error context.
     *
     * If rawInput is not null, this error comes from the [com.lemline.core.orchestrator.WorkflowOrchestrator.resumeFromTask] method
     * If rawOutput is not null, this error comes from the [com.lemline.core.orchestrator.WorkflowOrchestrator.resumeFromStartedTask] method
     *
     * @property taskStates The state information associated with the workflow at the time of failure.
     * @property nodePosition The position of the node in the workflow where the failure occurred.
     * @property rawInput The raw input data at the point of failure, if available.
     * @property rawOutput The raw output data at the point of failure, if available.
     * @property exception The exception that caused the workflow to fail.
     * @property error The serialized exception that caused the workflow to fail.
     */
    @ExperimentalTime
    @Serializable
    data class TaskFailed(
        override val taskStates: TaskStates,
        override val nodePosition: NodePosition,
        val rawInput: JsonElement?,
        val rawOutput: JsonElement?,
        val flowDirective: FlowDirective?,
        val error: InternalException.Error,
        val failedAt: Instant,
    ) : WorkflowEvent() {

        val exception: Exception get() = InternalException(error)

        constructor(
            taskStates: TaskStates,
            nodePosition: NodePosition,
            rawInput: JsonElement?,
            rawOutput: JsonElement?,
            flowDirective: FlowDirective?,
            exception: Exception,
            failedAt: Instant = Clock.System.now(),
        ) : this(
            taskStates = taskStates,
            nodePosition = nodePosition,
            rawInput = rawInput,
            rawOutput = rawOutput,
            flowDirective = flowDirective,
            error = InternalException.Error.fromUnexpectedException(exception, nodePosition),
            failedAt = failedAt
        )

        override fun toString() = "${this::class.simpleName}(" +
            "nodePosition=$nodePosition" +
            ", rawInput=$rawInput" +
            ", rawOutput=$rawOutput" +
            ", flowDirective=$flowDirective" +
            ", error=$error" +
            ", states=${taskStates.map { it.key.toString() + "=" + it.value }}" +
            ")"
    }

    /**
     * Represents the state of an activity that has been completed,
     * including information about the next node position,
     * the states involved, and the generated output.
     *
     * @property taskStates Represents a map containing workflow state.
     * @property nodePosition The position of the next node
     * @property rawInput The input of the next node
     * @property flowDirective The flow directive to be applied to the next node
     */
    @Serializable
    data class TaskScheduled(
        override val taskStates: TaskStates,
        override val nodePosition: NodePosition,
        val rawInput: JsonElement,
        val flowDirective: FlowDirective?
    ) : WorkflowEvent() {
        override fun toString() = "${this::class.simpleName}(" +
            "nodePosition=$nodePosition" +
            ", rawInput=$rawInput" +
            ", flowDirective=$flowDirective" +
            ", states=${taskStates.map { it.key.toString() + "=" + it.value }}" +
            ")"

        fun resume() = WorkflowCommand.ResumeFromTask(
            taskStates = taskStates,
            nodePosition = nodePosition,
            rawInput = rawInput,
            flowDirective = flowDirective,
        )
    }

    /**
     * Represents a result that indicates a wait is needed during processing.
     *
     * @property taskStates The states after the wait.
     * @property nodePosition Specifies the position of the wait task.
     * @property rawOutput Contains transformed input == raw output in the wait task.
     * @property waitUntil Defines the duration for which the wait is required.
     */
    @Serializable
    @ExperimentalTime
    data class WaitStarted(
        override val taskStates: TaskStates,
        override val nodePosition: NodePosition,
        val waitState: WaitState,
        val rawOutput: JsonElement,
        @Contextual val waitUntil: Instant
    ) : WorkflowEvent() {
        override fun toString() = "${this::class.simpleName}(" +
            "nodePosition=$nodePosition" +
            ", rawOutput=$rawOutput" +
            ", waitUntil=$waitUntil" +
            ", states=${taskStates.map { it.key.toString() + "=" + it.value }}" +
            ")"

        fun resume() = WorkflowCommand.ResumeFromStartedTask(
            taskStates = taskStates,
            nodePosition = nodePosition,
            rawOutput = rawOutput,
        )
    }

    /**
     * Represents a state where a retry is required for a specific node in the system.
     *
     * @property taskStates The states at retry.
     * @property nodePosition Specifies the position of the task to retry.
     * @property rawInput The raw input of the task to retry.
     * @property retryAt The time duration to wait before retrying.
     */
    @Serializable
    @ExperimentalTime
    data class RetryScheduled(
        override val taskStates: TaskStates,
        override val nodePosition: NodePosition,
        val rawInput: JsonElement,
        val flowDirective: FlowDirective?,
        val retryAt: Instant
    ) : WorkflowEvent() {
        override fun toString() = "${this::class.simpleName}(" +
            "nodePosition=$nodePosition" +
            ", rawInput=$rawInput" +
            ", flowDirective=$flowDirective" +
            ", retryAt=$retryAt" +
            ", states=${taskStates.map { it.key.toString() + "=" + it.value }}" +
            ")"

        fun resume() = WorkflowCommand.ResumeFromTask(
            taskStates = taskStates,
            nodePosition = nodePosition,
            rawInput = rawInput,
            flowDirective = flowDirective,
        )
    }


    /**
     * Represents a result state where a sub-workflow needs to be initiated.
     *
     * @property taskStates Represents a map containing the workflow state.
     * @property nodePosition Specifies the position of the RunWorkflow node
     * @property rawInput The transformed input of the run workflow task.
     * @property childConfig Configuration details specifying the child workflow to be started.
     */
    @Serializable
    data class RunWorkflowStarted(
        override val taskStates: TaskStates,
        override val nodePosition: NodePosition,
        val runState: RunState,
        val rawInput: JsonElement,
        val childConfig: RunWorkflowException.Config,
    ) : WorkflowEvent() {
        override fun toString() = "${this::class.simpleName}(" +
            "nodePosition=$nodePosition" +
            ", runState=$runState" +
            ", transformedInput=$rawInput" +
            ", childConfig=$childConfig" +
            ", states=${taskStates.map { it.key.toString() + "=" + it.value }}" +
            ")"

        fun resumeSync(rawOutput: JsonElement) = WorkflowCommand.ResumeFromStartedTask(
            taskStates = taskStates,
            nodePosition = nodePosition,
            rawOutput = rawOutput,
        )

        fun resumeAsync() = WorkflowCommand.ResumeFromStartedTask(
            taskStates = taskStates,
            nodePosition = nodePosition,
            rawOutput = rawInput,
        )
    }

    /**
     * Represents the starting state of a workflow fork operation.
     *
     * A fork operation allows parallel execution of multiple branches within a workflow.
     * This class captures the state of the fork, the input data, and the position of the fork
     * node within the workflow graph.
     *
     * @property forkState Describes the current state of the fork, encompassing information
     * such as the start time and the last completed branch, if any.
     * @property rawInput Represents the raw JSON input data associated with the fork operation.
     * This data is provided to the forked branches at their starting point.
     */
    @Serializable
    data class ForkStarted(
        override val taskStates: TaskStates,
        override val nodePosition: NodePosition,
        val forkState: ForkState,
        val rawInput: JsonElement,
    ) : WorkflowEvent() {
        override fun toString() = "${this::class.simpleName}(" +
            "nodePosition=$nodePosition" +
            ", forkState=$forkState" +
            ", rawInput=$rawInput" +
            ", states=${taskStates.map { it.key.toString() + "=" + it.value }}" +
            ")"

        fun resume(rawOutput: JsonElement) = WorkflowCommand.ResumeFromStartedTask(
            taskStates = taskStates,
            nodePosition = nodePosition,
            rawOutput = rawOutput,
        )

        fun startBranch(branchPosition: NodePosition) = WorkflowCommand.ResumeFromTask(
            taskStates = taskStates,
            nodePosition = branchPosition,
            rawInput = rawInput,
            flowDirective = null,
        )
    }

    /**
     * Represents a state indicating that a branch in a fork has been completed.
     *
     * @property taskStates The states after the wait.
     * @property nodePosition Specifies the position of the fork task.
     * @property branchName The name of the completed branch.
     * @property output The raw JSON output of the completed branch.
     * @property flowDirective An optional flow directive specifying the next steps in the workflow.
     */
    @ExperimentalTime
    @Serializable
    data class ForkBranchCompleted(
        override val taskStates: TaskStates,
        override val nodePosition: NodePosition,
        val branchName: String,
        val output: JsonElement,
        val completedAt: Instant,
        val flowDirective: FlowDirective?
    ) : WorkflowEvent() {
        override fun toString() = "${this::class.simpleName}(" +
            "nodePosition=$nodePosition" +
            ", branchName=$branchName" +
            ", transformedInput=$output" +
            ", flowDirective=$flowDirective" +
            ", states=${taskStates.map { it.key.toString() + "=" + it.value }}" +
            ")"
    }
}

/**
 * Status of a branch execution.
 * Used by the runner module for database tracking.
 */
@Serializable
enum class BranchStatus {
    PENDING,    // Not yet started
    RUNNING,    // Currently executing
    COMPLETED,  // Successfully finished
    FAULTED     // Failed with error
}
