syntax = "proto3";

package lemline.internal.v1;

import "google/protobuf/timestamp.proto";
import "internal/common.proto";
import "internal/node_state.proto";

option java_multiple_files = true;
option java_package = "com.lemline.messages.internal.v1";

message MessageMetadata {
  string workflow_id = 1;
  string node_position = 2;
  google.protobuf.Timestamp emitted_at = 3;
}

message InternalMessageEnvelope {
  string message_type = 1;
  int32 schema_version = 2;
  WorkflowInfoMessage workflow_info = 3;
  MessageMetadata metadata = 4;
  oneof payload {
    WorkflowCommandMessage command = 10;
    WorkflowEventMessage event = 11;
  }
}

message WorkflowCommandMessage {
  oneof command {
    ResumeFromTaskCommand resume_from_task = 1;
    ResumeWithCompletedTaskCommand resume_with_completed_task = 2;
    ResumeWithFailedTaskCommand resume_with_failed_task = 3;
  }
}

message ResumeFromTaskCommand {
  NodeStackMessage node_stack = 1;
  string node_position = 2;
  string raw_input_json = 3;
  FlowDirectiveMessage flow_directive = 4;
}

message ResumeWithCompletedTaskCommand {
  NodeStackMessage node_stack = 1;
  string raw_output_json = 2;
}

message ResumeWithFailedTaskCommand {
  NodeStackMessage node_stack = 1;
  InternalErrorMessage error = 2;
}

message WorkflowEventMessage {
  oneof event {
    WorkflowCompletedEvent workflow_completed = 1;
    WorkflowFailedEvent workflow_failed = 2;
    ForkBranchCompletedEvent fork_branch_completed = 3;
    ForkBranchFailedEvent fork_branch_failed = 4;
    ForEachCompletedEvent for_each_completed = 5;
    TaskScheduledEvent task_scheduled = 6;
    WaitStartedEvent wait_started = 7;
    TaskRetryScheduledEvent task_retry_scheduled = 8;
    RunWorkflowStartedEvent run_workflow_started = 9;
    ForkStartedEvent fork_started = 10;
    ListenStartedEvent listen_started = 11;
    EmitStartedEvent emit_started = 12;
    CallHttpStartedEvent call_http_started = 13;
    RunScriptStartedEvent run_script_started = 14;
    RunShellStartedEvent run_shell_started = 15;
  }
}

message WorkflowStatePayload {
  oneof state {
    WorkflowCommandMessage command = 1;
    WorkflowEventMessage event = 2;
  }
}

message WaitConfigMessage {
  google.protobuf.Timestamp wait_until = 1;
}

message RunWorkflowConfigMessage {
  string namespace = 1;
  string name = 2;
  string version = 3;
  string input_json = 4;
  bool sync = 5;
}

enum ListenStrategyMessage {
  LISTEN_STRATEGY_MESSAGE_UNSPECIFIED = 0;
  LISTEN_STRATEGY_MESSAGE_ONE = 1;
  LISTEN_STRATEGY_MESSAGE_ANY = 2;
  LISTEN_STRATEGY_MESSAGE_ALL = 3;
}

enum ListenReadAsMessage {
  LISTEN_READ_AS_MESSAGE_UNSPECIFIED = 0;
  LISTEN_READ_AS_MESSAGE_DATA = 1;
  LISTEN_READ_AS_MESSAGE_ENVELOPE = 2;
  LISTEN_READ_AS_MESSAGE_RAW = 3;
}

message CorrelationDefMessage {
  string from = 1;
  optional string expect = 2;
}

message CorrelationMapMessage {
  map<string, CorrelationDefMessage> values = 1;
}

message EventFilterMessage {
  optional string type = 1;
  optional string source = 2;
  optional string subject = 3;
  optional string id = 4;
  optional string datacontenttype = 5;
  optional string dataschema = 6;
  optional string time = 7;
  optional string data_filter = 8;
  CorrelationMapMessage correlations = 9;
}

message UntilConditionMessage {
  oneof value {
    string expression = 1;
    EventFilterMessage event_filter = 2;
  }
}

message ListenConfigMessage {
  ListenStrategyMessage strategy = 1;
  repeated EventFilterMessage filters = 2;
  UntilConditionMessage until = 3;
  ListenReadAsMessage read_as = 4;
  google.protobuf.Timestamp timeout_at = 5;
  optional string correlation_context_json = 6;
}

message StringMapMessage {
  map<string, string> values = 1;
}

message EmitConfigMessage {
  string id = 1;
  string source = 2;
  string type = 3;
  optional string time = 4;
  optional string subject = 5;
  optional string dataschema = 6;
  optional string datacontenttype = 7;
  optional string data_json = 8;
  StringMapMessage extensions = 9;
}

message BasicAuthMessage {
  string username = 1;
  string password = 2;
}

message BearerAuthMessage {
  string token = 1;
}

message OAuth2AuthMessage {
  string token = 1;
  string token_type = 2;
}

message HttpAuthenticationMessage {
  oneof value {
    BasicAuthMessage basic = 1;
    BearerAuthMessage bearer = 2;
    OAuth2AuthMessage oauth2 = 3;
  }
}

enum HttpOutputMessage {
  HTTP_OUTPUT_MESSAGE_UNSPECIFIED = 0;
  HTTP_OUTPUT_MESSAGE_RAW = 1;
  HTTP_OUTPUT_MESSAGE_CONTENT = 2;
  HTTP_OUTPUT_MESSAGE_RESPONSE = 3;
}

enum ProcessReturnTypeMessage {
  PROCESS_RETURN_TYPE_MESSAGE_UNSPECIFIED = 0;
  PROCESS_RETURN_TYPE_MESSAGE_NONE = 1;
  PROCESS_RETURN_TYPE_MESSAGE_STDOUT = 2;
  PROCESS_RETURN_TYPE_MESSAGE_STDERR = 3;
  PROCESS_RETURN_TYPE_MESSAGE_CODE = 4;
  PROCESS_RETURN_TYPE_MESSAGE_ALL = 5;
}

message CallHttpConfigMessage {
  string method = 1;
  string url = 2;
  map<string, string> headers = 3;
  map<string, string> query = 4;
  optional string body_json = 5;
  HttpOutputMessage output = 6;
  bool redirect = 7;
  HttpAuthenticationMessage authentication = 8;
}

message RunScriptConfigMessage {
  string language = 1;
  string code = 2;
  StringMapMessage arguments = 3;
  StringMapMessage environment = 4;
  bool await = 5;
  ProcessReturnTypeMessage return_type = 6;
}

message RunShellConfigMessage {
  string command = 1;
  StringMapMessage arguments = 2;
  StringMapMessage environment = 3;
  bool await = 4;
  ProcessReturnTypeMessage return_type = 5;
}

message WorkflowCompletedEvent {
  string output_json = 1;
  google.protobuf.Timestamp completed_at = 2;
  NodeStackMessage node_stack = 3;
}

message WorkflowFailedEvent {
  NodeStackMessage node_stack = 1;
  optional string raw_input_json = 2;
  optional string raw_output_json = 3;
  FlowDirectiveMessage flow_directive = 4;
  InternalErrorMessage error = 5;
  google.protobuf.Timestamp failed_at = 6;
}

message ForkBranchCompletedEvent {
  NodeStackMessage node_stack = 1;
  string branch_position = 2;
  string branch_output_json = 3;
  google.protobuf.Timestamp completed_at = 4;
}

message ForkBranchFailedEvent {
  NodeStackMessage node_stack = 1;
  string branch_position = 2;
  InternalErrorMessage error = 3;
  google.protobuf.Timestamp failed_at = 4;
}

message ForEachCompletedEvent {
  NodeStackMessage node_stack = 1;
  string output_json = 2;
}

message TaskScheduledEvent {
  NodeStackMessage node_stack = 1;
  string node_position = 2;
  string raw_input_json = 3;
  FlowDirectiveMessage flow_directive = 4;
}

message WaitStartedEvent {
  NodeStackMessage node_stack = 1;
  string raw_output_json = 2;
  WaitConfigMessage config = 3;
}

message TaskRetryScheduledEvent {
  NodeStackMessage node_stack = 1;
  string node_position = 2;
  string raw_input_json = 3;
  FlowDirectiveMessage flow_directive = 4;
  google.protobuf.Timestamp retry_at = 5;
}

message RunWorkflowStartedEvent {
  NodeStackMessage node_stack = 1;
  string raw_input_json = 2;
  RunWorkflowConfigMessage config = 3;
}

message ForkStartedEvent {
  NodeStackMessage node_stack = 1;
  string raw_input_json = 2;
}

message ListenStartedEvent {
  NodeStackMessage node_stack = 1;
  string raw_output_json = 2;
  ListenConfigMessage config = 3;
}

message EmitStartedEvent {
  NodeStackMessage node_stack = 1;
  string input_json = 2;
  EmitConfigMessage config = 3;
}

message CallHttpStartedEvent {
  NodeStackMessage node_stack = 1;
  string input_json = 2;
  CallHttpConfigMessage config = 3;
}

message RunScriptStartedEvent {
  NodeStackMessage node_stack = 1;
  string input_json = 2;
  RunScriptConfigMessage config = 3;
}

message RunShellStartedEvent {
  NodeStackMessage node_stack = 1;
  string input_json = 2;
  RunShellConfigMessage config = 3;
}
