// SPDX-License-Identifier: BUSL-1.1
package com.lemline.runner.cli.config

import com.lemline.runner.common.config.DatabaseType
import com.lemline.runner.common.config.MessagingType
import io.kotest.assertions.throwables.shouldThrow
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import org.junit.jupiter.api.Test

class ConfigTemplateGeneratorTest {

    private val generator = ConfigTemplateGenerator()

    @Test
    fun `test kafka postgres combination`() {
        val config = generator.generate(MessagingType.KAFKA, DatabaseType.POSTGRESQL)

        config shouldContain "# Lemline Configuration: Kafka + PostgreSQL"
        config shouldContain "# Generated by: lemline config create"
        config shouldContain "docker compose --profile kafka-pg up -d"
        config shouldContain "LEMLINE_CONFIG=./lemline.yaml lemline listen"

        // Database section
        config shouldContain "database:"
        config shouldContain "postgresql:"
        config shouldContain "host: localhost"
        config shouldContain "port: 5432"
        config shouldContain "database: lemline"
        config shouldContain "username: postgres"
        config shouldContain $$"password: ${LEMLINE_PG_PASSWORD:postgres}"

        // Messaging section
        config shouldContain "messaging:"
        config shouldContain "kafka:"
        config shouldContain "brokers: localhost:9092"

        // Should not contain other types
        config shouldNotContain "mysql:"
        config shouldNotContain "rabbitmq:"
        config shouldNotContain "pgmq:"
    }

    @Test
    fun `test kafka mysql combination`() {
        val config = generator.generate(MessagingType.KAFKA, DatabaseType.MYSQL)

        config shouldContain "# Lemline Configuration: Kafka + MySQL"
        config shouldContain "docker compose --profile kafka-mysql up -d"

        // Database section
        config shouldContain "mysql:"
        config shouldContain "port: 3306"
        config shouldContain "username: lemline"
        config shouldContain $$"password: ${LEMLINE_MYSQL_PASSWORD:lemline}"

        // Messaging section
        config shouldContain "kafka:"
        config shouldContain "brokers: localhost:9092"

        // Should not contain other types
        config shouldNotContain "postgresql:"
        config shouldNotContain "rabbitmq:"
        config shouldNotContain "pgmq:"
    }

    @Test
    fun `test rabbitmq postgres combination`() {
        val config = generator.generate(MessagingType.RABBITMQ, DatabaseType.POSTGRESQL)

        config shouldContain "# Lemline Configuration: RabbitMQ + PostgreSQL"
        config shouldContain "docker compose --profile rabbit-pg up -d"

        // Database section
        config shouldContain "postgresql:"
        config shouldContain $$"password: ${LEMLINE_PG_PASSWORD:postgres}"

        // Messaging section
        config shouldContain "rabbitmq:"
        config shouldContain "hostname: localhost"
        config shouldContain "port: 5672"
        config shouldContain "username: guest"
        config shouldContain "password: guest"

        // Should not contain other types
        config shouldNotContain "mysql:"
        config shouldNotContain "kafka:"
        config shouldNotContain "pgmq:"
    }

    @Test
    fun `test rabbitmq mysql combination`() {
        val config = generator.generate(MessagingType.RABBITMQ, DatabaseType.MYSQL)

        config shouldContain "# Lemline Configuration: RabbitMQ + MySQL"
        config shouldContain "docker compose --profile rabbit-mysql up -d"

        // Database section
        config shouldContain "mysql:"
        config shouldContain $$"password: ${LEMLINE_MYSQL_PASSWORD:lemline}"

        // Messaging section
        config shouldContain "rabbitmq:"

        // Should not contain other types
        config shouldNotContain "postgresql:"
        config shouldNotContain "kafka:"
    }

    @Test
    fun `test pgmq postgres combination`() {
        val config = generator.generate(MessagingType.PGMQ, DatabaseType.POSTGRESQL)

        config shouldContain "# Lemline Configuration: PGMQ + PostgreSQL"
        config shouldContain "docker compose --profile pgmq up -d"

        // Database section
        config shouldContain "postgresql:"
        config shouldContain $$"password: ${LEMLINE_PG_PASSWORD:postgres}"

        // Messaging section
        config shouldContain "pgmq:"
        config shouldContain "host: localhost"
        config shouldContain "port: 5432"
        config shouldContain "database: lemline"
        config shouldContain "username: postgres"
        config shouldContain $$"password: ${LEMLINE_PGMQ_PASSWORD:postgres}"

        // Should not contain other types
        config shouldNotContain "mysql:"
        config shouldNotContain "kafka:"
        config shouldNotContain "rabbitmq:"
    }

    @Test
    fun `test pgmq mysql combination`() {
        val config = generator.generate(MessagingType.PGMQ, DatabaseType.MYSQL)

        config shouldContain "# Lemline Configuration: PGMQ + MySQL"
        config shouldContain "docker compose --profile pgmq-mysql up -d"

        // Database section
        config shouldContain "mysql:"
        config shouldContain $$"password: ${LEMLINE_MYSQL_PASSWORD:lemline}"

        // Messaging section
        config shouldContain "pgmq:"

        // Should not contain other types
        config shouldNotContain "postgresql:"
        config shouldNotContain "kafka:"
        config shouldNotContain "rabbitmq:"
    }

    @Test
    fun `test IN_MEMORY messaging is rejected`() {
        shouldThrow<IllegalArgumentException> {
            generator.generate(MessagingType.IN_MEMORY, DatabaseType.POSTGRESQL)
        }
    }

    @Test
    fun `test H2 database is rejected`() {
        shouldThrow<IllegalArgumentException> {
            generator.generate(MessagingType.KAFKA, DatabaseType.H2)
        }
    }

    @Test
    fun `test all configs contain header comment`() {
        val combinations = listOf(
            MessagingType.KAFKA to DatabaseType.POSTGRESQL,
            MessagingType.KAFKA to DatabaseType.MYSQL,
            MessagingType.RABBITMQ to DatabaseType.POSTGRESQL,
            MessagingType.RABBITMQ to DatabaseType.MYSQL,
            MessagingType.PGMQ to DatabaseType.POSTGRESQL,
            MessagingType.PGMQ to DatabaseType.MYSQL,
        )

        combinations.forEach { (messaging, database) ->
            val config = generator.generate(messaging, database)
            config shouldContain "# Lemline Configuration:"
            config shouldContain "# Generated by: lemline config create"
            config shouldContain "# Start infrastructure:"
            config shouldContain "# Run Lemline:"
        }
    }

    @Test
    fun `test all configs have proper YAML structure`() {
        val combinations = listOf(
            MessagingType.KAFKA to DatabaseType.POSTGRESQL,
            MessagingType.RABBITMQ to DatabaseType.MYSQL,
            MessagingType.PGMQ to DatabaseType.POSTGRESQL,
        )

        combinations.forEach { (messaging, database) ->
            val config = generator.generate(messaging, database)
            config shouldContain "lemline:"
            config shouldContain "  database:"
            config shouldContain "  messaging:"
        }
    }
}
