version: '3.8'

services:
  postgres:
    image: postgres:15 # Or your preferred version
    container_name: lemline-postgres
    environment:
      POSTGRES_DB: lemline_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lemline-net

volumes:
  postgres_data:

networks:
  lemline-net:
    driver: bridge 