// SPDX-License-Identifier: BUSL-1.1
package com.lemline.runner.cli.config

import com.lemline.runner.common.config.DatabaseType
import com.lemline.runner.common.config.MessagingType

/**
 * Generates YAML configuration templates for different messaging and database combinations.
 */
class ConfigTemplateGenerator {

    /**
     * Generates a complete YAML configuration for the given messaging and database types.
     *
     * @param messagingType The messaging/broker type (KAFKA, RABBITMQ, PGMQ)
     * @param databaseType The database type (POSTGRESQL, MYSQL)
     * @return YAML configuration as a string
     */
    fun generate(messagingType: MessagingType, databaseType: DatabaseType): String {
        require(messagingType != MessagingType.IN_MEMORY) {
            "IN_MEMORY messaging is not supported for production configurations"
        }
        require(databaseType != DatabaseType.H2) {
            "H2 database is not supported for production configurations"
        }

        val profile = getDockerComposeProfile(messagingType, databaseType)
        val messagingDisplay = getDisplayName(messagingType)
        val databaseDisplay = getDisplayName(databaseType)

        return """
            |# Lemline Configuration: $messagingDisplay + $databaseDisplay
            |# Generated by: lemline config create
            |#
            |# Start infrastructure:
            |#   docker compose --profile $profile up -d
            |#
            |# Run Lemline:
            |#   LEMLINE_CONFIG=./lemline.yaml lemline listen
            |
            |lemline:
            |${getDatabaseSection(databaseType)}
            |${getMessagingSection(messagingType)}
            """.trimMargin()
    }

    private fun getDatabaseSection(databaseType: DatabaseType): String {
        return when (databaseType) {
            DatabaseType.POSTGRESQL -> $$"""
                |  database:
                |    postgresql:
                |      host: localhost
                |      port: 5432
                |      database: lemline
                |      username: postgres
                |      password: ${LEMLINE_PG_PASSWORD:postgres}
            """.trimMargin()

            DatabaseType.MYSQL -> $$"""
                |  database:
                |    mysql:
                |      host: localhost
                |      port: 3306
                |      database: lemline
                |      username: lemline
                |      password: ${LEMLINE_MYSQL_PASSWORD:lemline}
            """.trimMargin()

            DatabaseType.H2 -> error("H2 database is not supported for production configurations")
        }
    }

    private fun getMessagingSection(messagingType: MessagingType): String {
        return when (messagingType) {
            MessagingType.KAFKA -> """
                |  messaging:
                |    kafka:
                |      brokers: localhost:9092
            """.trimMargin()

            MessagingType.RABBITMQ -> """
                |  messaging:
                |    rabbitmq:
                |      hostname: localhost
                |      port: 5672
                |      username: guest
                |      password: guest
            """.trimMargin()

            MessagingType.PGMQ -> $$"""
                |  messaging:
                |    pgmq:
                |      host: localhost
                |      port: 5432
                |      database: lemline
                |      username: postgres
                |      password: ${LEMLINE_PGMQ_PASSWORD:postgres}
            """.trimMargin()

            MessagingType.IN_MEMORY -> error("IN_MEMORY messaging is not supported for production configurations")
        }
    }

    private fun getDockerComposeProfile(messagingType: MessagingType, databaseType: DatabaseType): String {
        return when (messagingType) {
            MessagingType.KAFKA -> when (databaseType) {
                DatabaseType.POSTGRESQL -> "kafka-pg"
                DatabaseType.MYSQL -> "kafka-mysql"
                DatabaseType.H2 -> error("H2 not supported")
            }

            MessagingType.RABBITMQ -> when (databaseType) {
                DatabaseType.POSTGRESQL -> "rabbit-pg"
                DatabaseType.MYSQL -> "rabbit-mysql"
                DatabaseType.H2 -> error("H2 not supported")
            }

            MessagingType.PGMQ -> when (databaseType) {
                DatabaseType.POSTGRESQL -> "pgmq"
                DatabaseType.MYSQL -> "pgmq-mysql"
                DatabaseType.H2 -> error("H2 not supported")
            }

            MessagingType.IN_MEMORY -> error("IN_MEMORY not supported")
        }
    }

    private fun getDisplayName(messagingType: MessagingType): String {
        return when (messagingType) {
            MessagingType.KAFKA -> "Kafka"
            MessagingType.RABBITMQ -> "RabbitMQ"
            MessagingType.PGMQ -> "PGMQ"
            MessagingType.IN_MEMORY -> "InMemory"
        }
    }

    private fun getDisplayName(databaseType: DatabaseType): String {
        return when (databaseType) {
            DatabaseType.POSTGRESQL -> "PostgreSQL"
            DatabaseType.MYSQL -> "MySQL"
            DatabaseType.H2 -> "H2"
        }
    }
}
