CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS public.lemline_lifecycle_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(255) NOT NULL,
    source VARCHAR(2048) NOT NULL,
    type VARCHAR(255) NOT NULL,
    specversion VARCHAR(16) NOT NULL,
    subject VARCHAR(2048) NULL,
    event_time TIMESTAMP WITH TIME ZONE NULL,
    datacontenttype VARCHAR(255) NULL,
    dataschema VARCHAR(2048) NULL,
    lemline_workflow_id UUID NULL,
    lemline_workflow_namespace VARCHAR(255) NULL,
    lemline_workflow_name VARCHAR(255) NULL,
    lemline_workflow_version VARCHAR(255) NULL,
    payload CLOB NOT NULL,
    ingested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT uq_lemline_lifecycle_events_source_event_id UNIQUE (source, event_id)
);

CREATE INDEX IF NOT EXISTS idx_lemline_lifecycle_events_event_time
    ON public.lemline_lifecycle_events (event_time);

CREATE INDEX IF NOT EXISTS idx_lemline_lifecycle_events_type
    ON public.lemline_lifecycle_events (type);

CREATE INDEX IF NOT EXISTS idx_lemline_lifecycle_events_workflow_name_version
    ON public.lemline_lifecycle_events (lemline_workflow_name, lemline_workflow_version);

CREATE INDEX IF NOT EXISTS idx_lemline_lifecycle_events_workflow_id
    ON public.lemline_lifecycle_events (lemline_workflow_id);
