name: Build and Deploy Writerside Documentation

on:
  push:
    branches: [ "main" ]
    paths:
      - 'lemline-docs/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  INSTANCE: 'lemline-docs/docs'  # Adjust 'hi' if your instance ID differs
  DOCKER_VERSION: '2025.04.8412'  # Use the latest Writerside Docker version

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      docs_changed: ${{ steps.filter.outputs.docs_changed }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docs_changed:
              - 'lemline-docs/**'

  build:
    needs: check_changes
    if: needs.check_changes.outputs.docs_changed == 'true'
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.define-ids.outputs.artifact }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Define Artifact Name
        id: define-ids
        run: |
          INSTANCE_ID=${INSTANCE#*/}
          INSTANCE_ID_UPPER=$(echo "$INSTANCE_ID" | tr '[:lower:]' '[:upper:]')
          ARTIFACT="webHelp${INSTANCE_ID_UPPER}2-all.zip"
          echo "artifact=$ARTIFACT" >> $GITHUB_OUTPUT
          echo "INSTANCE_ID_UPPER=$INSTANCE_ID_UPPER" >> $GITHUB_ENV

      - name: Build Documentation
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            artifacts/${{ steps.define-ids.outputs.artifact }}
            artifacts/report.json
          retention-days: 7

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: artifacts

      - name: Unzip Artifact
        run: unzip -O UTF-8 -qq "artifacts/${{ needs.build.outputs.artifact }}" -d dir

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dir

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
